// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCrvOR8a23KZhXI4t2vYVF2qjAerl7UD4',
    appId: '1:396480238762:web:6912c465dfe8bb8eaf2cd3',
    messagingSenderId: '396480238762',
    projectId: 'black-dragon-411407',
    authDomain: 'black-dragon-411407.firebaseapp.com',
    storageBucket: 'black-dragon-411407.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKy2l0C9643e8grBwqnFpUjdHZggWKA8',
    appId: '1:396480238762:android:f04f0fe443bb959eaf2cd3',
    messagingSenderId: '396480238762',
    projectId: 'black-dragon-411407',
    storageBucket: 'black-dragon-411407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0T_kuqUMFayCzYTWyhCklcaHyFjbul9s',
    appId: '1:396480238762:ios:d4c96813eb9668a5af2cd3',
    messagingSenderId: '396480238762',
    projectId: 'black-dragon-411407',
    storageBucket: 'black-dragon-411407.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0T_kuqUMFayCzYTWyhCklcaHyFjbul9s',
    appId: '1:396480238762:ios:d4c96813eb9668a5af2cd3',
    messagingSenderId: '396480238762',
    projectId: 'black-dragon-411407',
    storageBucket: 'black-dragon-411407.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCrvOR8a23KZhXI4t2vYVF2qjAerl7UD4',
    appId: '1:396480238762:web:d6a0fd97ca02e515af2cd3',
    messagingSenderId: '396480238762',
    projectId: 'black-dragon-411407',
    authDomain: 'black-dragon-411407.firebaseapp.com',
    storageBucket: 'black-dragon-411407.firebasestorage.app',
  );
}
